#!/usr/bin/env bash
set -euo pipefail

IMAGE="${1:?Usage: test-generate.sh IMAGE:TAG}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== Test 1: score-k8s binary exists ==="
docker run --rm "$IMAGE" score-k8s --version
echo "PASS"

echo ""
echo "=== Test 2: provisioners directory exists ==="
docker run --rm "$IMAGE" ls /opt/provisioners/
echo "PASS"

echo ""
echo "=== Test 3: plugin.yaml is in the correct location ==="
docker run --rm "$IMAGE" cat /home/argocd/cmp-server/config/plugin.yaml | grep -q "score-k8s"
echo "PASS"

echo ""
echo "=== Test 4: single score file — init + generate cycle ==="
OUTPUT=$(docker run --rm \
  -v "${SCRIPT_DIR}/score-test.yaml:/src/score-test.yaml:ro" \
  -e ARGOCD_ENV_IMAGE=nginx:1.25 \
  -e ARGOCD_ENV_NAMESPACE=test-ns \
  --user 999 \
  "$IMAGE" \
  sh -c '
    cp /src/score-test.yaml /tmp/score.yaml && cd /tmp &&
    score-k8s init --no-sample 2>/dev/null &&
    score-k8s generate score.yaml \
      --image "${ARGOCD_ENV_IMAGE}" \
      --namespace "${ARGOCD_ENV_NAMESPACE}" \
      -o - 2>/dev/null
  ')

if echo "$OUTPUT" | grep -q "apiVersion"; then
  echo "PASS: output contains Kubernetes manifests"
else
  echo "FAIL: output does not contain Kubernetes manifests"
  echo "Output was:"
  echo "$OUTPUT"
  exit 1
fi

if echo "$OUTPUT" | grep -q "nginx:1.25"; then
  echo "PASS: image override applied"
else
  echo "FAIL: image override not found in output"
  exit 1
fi

if echo "$OUTPUT" | grep -q "test-ns"; then
  echo "PASS: namespace override applied"
else
  echo "FAIL: namespace override not found in output"
  exit 1
fi

echo ""
echo "=== Test 5: multi-workload generation with per-workload images ==="
OUTPUT=$(docker run --rm \
  -v "${SCRIPT_DIR}/backend.score.yaml:/src/backend.score.yaml:ro" \
  -v "${SCRIPT_DIR}/frontend.score.yaml:/src/frontend.score.yaml:ro" \
  -e ARGOCD_ENV_IMAGE_backend=my-registry/backend:v1.0 \
  -e ARGOCD_ENV_IMAGE_frontend=my-registry/frontend:v2.0 \
  -e ARGOCD_ENV_NAMESPACE=multi-ns \
  -e ARGOCD_ENV_DOMAIN=app.example.com \
  --user 999 \
  "$IMAGE" \
  bash -c '
    cp /src/*.score.yaml /tmp/ && cd /tmp &&
    PROV_FLAGS="" &&
    for f in /opt/provisioners/*.provisioners.yaml; do
      [ -f "$f" ] && PROV_FLAGS="$PROV_FLAGS --provisioners $f"
    done &&
    score-k8s init --no-sample $PROV_FLAGS 2>/dev/null &&
    for f in *.score.yaml; do
      workload="${f%.score.yaml}"
      img_var="ARGOCD_ENV_IMAGE_${workload}"
      img="${!img_var:-${ARGOCD_ENV_IMAGE:-placeholder:latest}}"
      score-k8s generate "$f" \
        --image "$img" \
        --namespace "${ARGOCD_ENV_NAMESPACE:-default}" \
        2>/dev/null
    done
    cat manifests.yaml
  ')

if echo "$OUTPUT" | grep -q "my-registry/backend:v1.0"; then
  echo "PASS: backend image override applied"
else
  echo "FAIL: backend image override not found"
  echo "Output was:"
  echo "$OUTPUT"
  exit 1
fi

if echo "$OUTPUT" | grep -q "my-registry/frontend:v2.0"; then
  echo "PASS: frontend image override applied"
else
  echo "FAIL: frontend image override not found"
  exit 1
fi

if echo "$OUTPUT" | grep -q "multi-ns"; then
  echo "PASS: namespace override applied to multi-workload output"
else
  echo "FAIL: namespace override not found in multi-workload output"
  exit 1
fi

if echo "$OUTPUT" | grep -q "pgvector"; then
  echo "PASS: pgvector postgres provisioner used"
else
  echo "FAIL: pgvector image not found (custom postgres provisioner not loaded)"
  exit 1
fi

if echo "$OUTPUT" | grep -q "HTTPRoute"; then
  echo "PASS: HTTPRoute generated by route provisioner"
else
  echo "FAIL: HTTPRoute not found in output"
  exit 1
fi

echo ""
echo "=== All tests passed ==="
